- components/topbar/src/application-menu.tsx
The selected application in the app menu should still have the beta label.
> fix(topbar): add beta label to selected app

- .github/dependabot.yml
Add explicit prefix to dependabot to make commit linter happy (following conventional commits).
> chore: set fixed commit prefix dependabot

- components/notification-bar/package.json
- components/password-input/package.json
- components/slider/package.json
- components/stepper/package.json
- components/topbar/package.json
- icons/package.json
- pnpm-lock.yaml
- styles/package.json
- theme/package.json
Removed dev-deps listed as peers since peers autoinstall in pnpm, will simplyfy maintenance of deps aswell
> chore(deps): clear dev-deps listed as peers

- components/topbar/src/organization-menu.tsx
- examples/src/components/top-bar.tsx
Hides a wrapper div and a Divider if there is custom content e.g. "Create organization", but no organizations.
This supports the case where the user has not yet created an organization or accepted an invitation, and the one where the organization list is still loading.
Before:
After:
> fix(topbar): support no orgs + custom content

- .github/workflows/verify-page.yml
- examples/.gitignore
- examples/package.json
- examples/playwright.confg.base.ts
- examples/playwright.config.ts
- examples/system-test/home-page.stest.ts
- examples/system-test/utils.ts
- examples/tsconfig.json
- examples/vite.config.ts
- pnpm-lock.yaml
Adds playwright system test to check gh-page, runs on new github workflow
This is the inital commit with core components for this purpose, it will be extended.
**github workflow trigger**
Currently only run on push main 
Also able to be triggered on dispatch for test
Also run on this branch currently, only temp (så u can see check)
- in **future** i plan this to run on schedueled interval as heartbeat test to verify gh-page
- also to run like 30min after push main (when gh-page deployed)
Also URLS to test with be added to variable in gh env eg (currently hardcoded)
**reporting**
It will only upload playwright report/artifact if test fails, can be found on github workflow summary page
Also i plan to send this report to team channel when fail :)
Artifact will contain screenshoot and more …
> chore: add playwright system test

- .github/workflows/deploy.yml
Aligned node version for deply.yml with all our others workflows (they use 18)
> chore: align node version for deploy workflow

- components/topbar/src/application.styles.ts
Set z-index of application menu icon rectangle to avoid it getting hidden under the button, which was the case when hovering the selected button during tab navigation.
> fix(topbar): application menu icon visible also when hovering selected button

- examples/src/stories/theme-page.tsx
Adds status color tokens to theme preview page:
> chore: add statusColor to theme preview

- examples/package.json
- examples/src/components/code-block.tsx
- examples/src/routing/route-map.tsx
- examples/src/stories/tab-list-utilities/tab-list-styled..tsx
- examples/src/stories/tab-list-utilities/tab-list-utilities-page.tsx
- pnpm-lock.yaml
- styles/package.json
- styles/src/index.ts
- styles/src/tab-list/tab-list.styles.ts
- styles/src/tab-list/tab.styles.ts
Exposes some new styles that can be used when styling fluent tablist, also added to example page with codeblock
> feat: add tablist utilities styles and examples

- components/slider/src/range-slider.spec.tsx
- components/slider/src/use-range-slider.ts
- examples/src/stories/slider/examples/range-slider-with-streps-and-marks-example.tsx
- examples/src/stories/slider/slider-page.tsx
- When a mark is the target of a click event, the slider will now snap to the value of the closest mark and not the specific clientX value.
-  Add example to slider page where both steps and marks are combined
- N/A
> fix(slider): snap to mark

- components/topbar/src/application-drawer.styles.ts
Minor style updates to application drawer
Left side before, right side after. (Just some more space...)
(And better icon-text-alignment, but that is not really visible in the example, but looks better with poptop)
> fix(topbar): application drawer style updates

- components/topbar/src/application-drawer.styles.ts
- components/topbar/src/application-drawer.tsx
Replace ToggleButton with regular Button in drawer to not get yellow icons in later Fluent versions.
> fix(topbar): do not use ToggleButton in drawer

- components/topbar/package.json
- components/topbar/src/translation-context.ts
- components/topbar/tsconfig.json
After the alignment of react version, the exported types in topbar was broken.
This fixes the types.
Also, a prebuild step is added for topbar as it requires icons to be build.
> Fix topbar types

- components/topbar/src/profile-language-submenu.styles.ts
Minor update to topbar language selector so that it looks better when only one language is supported.
Before:
After:
> fix(topbar): make language menu look ok for single language

- styles/src/static/static.styles.ts
Was just going to adapt the width and radius of scrollbar according to mocks:
https://www.figma.com/file/wIqVR0DqSc15Ocb5cG8W3q/Design-Guides?type=design&node-id=503-8392&mode=design&t=KWE9O4H8LEXTB5am-0
Ran into a new interesting issue, where chrome now is affected by the general "scrollbarWidth" that is needed for styling firefox.
Found a solution in the last entry in this amazing thread:
https://stackoverflow.com/questions/6165472/custom-css-scrollbar-for-firefox
Tested on Mac in Chrome, Firefox and Safari.
Tested on Windows in Chrome, Firefox and Edge.
(It does not look exactly the same in all browsers, but it looks ok)
> fix(styles): update scrollbar static styles

- examples/src/components/story/story-code-block-accordion.tsx
- examples/src/components/story/story-code-block.tsx
- examples/src/components/story/story-code-copy.tsx
Adjust copy code button for stories to be more easy to use and less "blocking" of code
copy-button now directly accessible from header and doesnt block example code as it somethimes did before
> chore: adjust story copy code button

- styles/src/static/static.styles.ts
New fix to the scroll conflicts with firefox and chrome.
There were browser warnings with the previous hack.
> fix(styles): handle firefox style without warning in chrome

- examples/src/components/story/story-code-block-accordion.tsx
- examples/src/components/story/story-code-copy.tsx
patch for examplepage copybutton, vilolating brutton as child to button. (accordion header is a button)
> chore: redesign copy code block icon example-page

- components/slider/package.json
- components/stepper/package.json
- components/topbar/package.json
- pnpm-lock.yaml
- theme/package.json
@fluentui/react-components, @fluentui/react-icons nor @fluentui/react-utilities no longer has a scheduler (0.20.0) peerDepencency.
Only @fluentui/react-context-selector as only used by examples has a scheduler (>=0.19.0 <=0.23.0) peerDependency.
We should remove the peerDependency to avoid unnecessary dependencies/warnings.
> chore: remove scheduler from peerDependencies

- components/topbar/src/context.spec.ts
- components/topbar/src/context.ts
Updated buildUrlWithContext so it does not duplicate query parameters if called with known parameters.
> fix(topbar): buildUrl utility function should not duplicate query parameters

- components/topbar/package.json
- components/topbar/src/application.styles.ts
- examples/src/stories/theme/components/color-tokens.tsx
- examples/src/stories/theme/theme-page.tsx
- pnpm-lock.yaml
- theme/docs/README.md
- theme/src/index.ts
- theme/tokens/generated/css/dark.css
- theme/tokens/generated/css/global.css
- theme/tokens/generated/css/light.css
- theme/tokens/generated/json/colors.json
- theme/tokens/generated/tokens/dark.json
- theme/tokens/generated/tokens/light.json
- theme/tokens/generated/ts/axisDarkTheme.ts
- theme/tokens/generated/ts/axisLightTheme.ts
- theme/tokens/generated/ts/base.ts
- theme/tokens/generated/ts/dark.ts
- theme/tokens/generated/ts/light.ts
- theme/tokens/generated/xaml/Colors.xaml
- theme/tokens/generated/xaml/ConstantResources.xaml
- theme/tokens/generated/xaml/Dark.xaml
- theme/tokens/generated/xaml/Light.xaml
* Add custom colors for axis to theme and export them in axisCustomTokens.
* Add a utility token that contains current selected theme.
* Generate new token files from axis theme
* Use custom tokens for my-X application styling in topbar.
This is a breaking change, since topbar requires the tokens to in the axis theme.
(hover, the application will not break if the custom token does not exist, it will just not show correct color)
Update of example page:
mySystems
myAxis
myBusiness
MyProducts
> custom theme colors

- illustrations/package.json
- pnpm-lock.yaml
Both lodash and yargs are bundled with the illustrations package for no good reason. Moving them to dev-dependencies instead.
> fix(illustrations): don't bundle lodash and yargs

- components/topbar/src/application-drawer.styles.ts
- components/topbar/src/application-drawer.tsx
- components/topbar/src/application-drawer.types.ts
- examples/src/components/top-bar.tsx
Update Drawer Trigger button to follow new Look from figma:
https://www.figma.com/design/RqNwSw0bq0sjSXT6M5uJGQ/My-Systems---Releases?node-id=2440-5383&m=dev
Will only be used when the property "triggerGroupShortName" is set in ApplicationDrawerContent.
If unset, the look will be unchanged.
**Old look:**
**New Look:**
> feat(topbar): add new look for application drawer trigger button when triggerGroupShortName is set

- components/slider/src/__snapshots__/range-slider.spec.tsx.snap
- components/slider/src/__snapshots__/slider.spec.tsx.snap
- components/slider/src/mark/label/mark-label.types.ts
- components/slider/src/mark/label/use-mark-label.ts
- components/slider/src/mark/mark.types.ts
- components/slider/src/range-slider.spec.tsx
- components/slider/src/render-slider.tsx
- components/slider/src/section/render-section.tsx
- components/slider/src/section/section.tsx
- components/slider/src/section/section.types.ts
- components/slider/src/section/use-section-styles.ts
- components/slider/src/section/use-section.ts
- components/slider/src/slider.types.ts
- components/slider/src/use-range-slider.ts
- components/slider/src/use-slider-styles.ts
- examples/src/stories/slider/examples/dual-section-example.tsx
- examples/src/stories/slider/examples/range-slider-with-section-example.tsx
- examples/src/stories/slider/examples/triple-section-example-rtl.tsx
- examples/src/stories/slider/examples/triple-section-example.tsx
- examples/src/stories/slider/examples/triple-section-no-zero-start-example.tsx
- examples/src/stories/slider/examples/with-range-example.tsx
- examples/src/stories/slider/slider-page.tsx
- tools/generated/changelog/changeset.js
- tools/src/changelog/changeset.ts
We need a slider with sections that have labels and customable track colors.
> feat(slider): add section labels support

- components/topbar/src/organization.styles.ts
Organisation menu now has the height fitting the content
- Fixes [LKPH-1993](https://jira.se.axis.com/browse/LKPH-1993)
> fix(topbar): content base height in organization menu

- components/slider/package.json
- components/slider/src/range-slider.spec.tsx
- components/slider/src/slider.spec.tsx
- components/slider/src/use-slider-styles.ts
- Fixes regression in slider introduced with https://github.com/AxisCommunications/fluent-components/pull/288 causing the backing input field (in thumb) not being disabled when the slider is passed the disabled prop.
> fix(slider): disable thumb input when slider disabled

- components/empty-view/package.json
- examples/tsconfig.json
- examples/vite.config.ts
- pnpm-lock.yaml
Adds empty-view path to vite config and tsconfig in examples. Removes unused deps from empty-view.
> fix: correct config files in examples

- components/empty-view/.eslintrc.json
- components/empty-view/package.json
- components/empty-view/src/constants.ts
- components/empty-view/src/index.ts
- components/empty-view/src/styles.ts
- components/empty-view/src/view.tsx
- components/empty-view/tsconfig.json
- components/empty-view/tsconfig.src.json
- components/password-input/package.json
- components/password-input/src/index.ts
- components/password-input/src/password-input.tsx
- hooks/package.json
- hooks/src/index.ts
- hooks/tsconfig.json
- pnpm-lock.yaml
The packages that export ES modules do not have a `.js` extension on the import paths, which means that the import path does not match an actual file path (since the latter do have a `.js` extension). This means they cannot be properly resolved by Node.js or the browser.
However, since we're using TypeScript to transpile, and we're using the legacy "node" module resolution, the import paths are preserved and end up not having a `.js` extension, while the transpiled files to have it.
There are two main ways to deal with this:
1. Use TS configuration `{"module":"esnext","moduleResolution":"bundler"}` and use a bundler that produces import paths matching an actual file. Note: using TypeScript in this case would leave the imports as-is and require users to use a bundler, so it would not …
> fix: node+browser compatible ES module import paths

- CHANGELOG.md
- components/empty-view/package.json
- components/password-input/package.json
- components/slider/package.json
- components/stepper/package.json
- components/topbar/package.json
- examples/package.json
- hooks/package.json
- icons/package.json
- illustrations/package.json
- package.json
- styles/package.json
- theme/package.json
- tools/generated/release/release.js
- tools/package.json
- tools/src/release/release.ts
- fix to use "alpha" when using any prerelease (so that it's
correctly tagged as "next" when publishing)
- release new breaking changes
> release: v11.0.0-alpha.0

- examples/src/stories/theme/components/color-tokens.tsx
There is not possible to filter tokens by value today from examplepage.
This small addition makes this possible
> chore: enable search by token value for example page

- styles/src/static/static.styles.ts
- Uses only standard css for scrollbar.
- This change allows us to use the Fluent `useScrollbarWidth` hook if needed.
Before
After -  Get arrows above/below scrollbar.
After -  Looks the same as before
`scrollbar-color` is not supported on Safari yet so the color is not the specified color. 
And it is shown only when the user scrolls the content.
(I didn't test it on the example page on Safari because I use Linux. But tested on the other app.)
Get arrows above/below scrollbar. Scrollbar edge is square.
> chore(styles): use standard styles for scrollbar
