AxisCommunications/fluent-components

components/topbar/src/top-bar.styles.ts
components/topbar/src/top-bar.tsx

Removed some styles so that the topbar looks correct with RTL direction.
**Before**
**After**

feat(topbar): support RTL direction in topbar

---

CHANGELOG.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json

- update code owners ([083559b](https://github.com/AxisCommunications/fluent-components/commit/083559b615642f3bf61d8a37694e73089e60c334))
- add dep-check sort script targets (#1) ([3cc1fc2](https://github.com/AxisCommunications/fluent-components/commit/3cc1fc2442d73f70f13504e2ec266ac526d280f3))
- **topbar**: support RTL direction in topbar (#3) ([51e9d59](https://github.com/AxisCommunications/fluent-components/commit/51e9d5946f3b2242e76c5615f9f09944b9ab50d6))

release: v8.0.0

---

changeset.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json

Re-release patch with `changeset.md` included

release: v8.0.1

---

examples/vite.config.ts

chore: add vite base path

---

CHANGELOG.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.1.0

---

.github/workflows/verify-icons.yml
.github/workflows/verify-tokens.yml

Run all verification instead of checking what's changed. This allows for setting all these as "required" for a PR without complex work-arounds.

chore: verify everything

---

CHANGELOG.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

- verify everything (#15) ([29c68fa](https://github.com/AxisCommunications/fluent-components/commit/29c68fa8350bafe24ce5351ddc349c14ce19e411))
- **topbar**: add beta label to selected app (#14) ([27f2067](https://github.com/AxisCommunications/fluent-components/commit/27f2067c1f71fa22bf9dcfc4cc92b9a3fe69746c))

release: v8.1.1

---

package.json

chore: remove unused script

---

README.md

Update the main readme file to link to the readme for all packages.

docs: link to package readmes from main readme

---

.github/dependabot.yml

fix: only use default npm registry

---

components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
theme/package.json
tools/package.json

Author is needed to be able to generate SBOM, hennce added in this PR

chore: add authors package.json

---

styles/package.json

Adds author for fluent-styles package, needed for SBOM

chore: add author for axis fluent-styles

---

CHANGELOG.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.2.0

---

components/topbar/src/application-menu.tsx
components/topbar/src/application.styles.ts

Per request from the UX-group, update selected App in dropdown to be highlighted.
Before:
After:
- Fixes https://jira.se.axis.com/browse/LKPH-1473

feat(topbar): change selected application from dismissed to highlighted

---

CHANGELOG.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.3.0

---

CHANGELOG.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

New patch release with topbar bugfix

release: v8.3.1

---

.github/workflows/verify-icons.yml
.github/workflows/verify-tokens.yml

Update github workflows for verify theme and icons to run against correct project :D

chore: update verify workflows to run on correct project

---

examples/src/landingpage/index.tsx

Adds an identifier for welcome page, needs for prepping system test :D

chore: add id to welcome page

---

.github/dependabot.yml

Adjust dependabot rebase-strategy to per auto rebase when behind main

chore: dependabot rebase-strategy to auto

---

CHANGELOG.md
components/notification-bar/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.4.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.6.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.7.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.7.1

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.8.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.9.0

---

examples/src/routing/route-map.tsx
examples/src/routing/routes.ts

Add route for tablist in examplepage, it did override passwordinput by mistake

chore: adjust example page route

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

adds tablist styles for fluent tablist component

release: v8.10.0

---

examples/src/stories/tab-list-utilities/tab-list-styled..tsx

typo fix codeblock for tab utilities

chore: fix typo in codeblock tablist

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

patch relase of tab style color

release: v8.10.1

---

styles/src/index.ts
styles/src/navigation/navigation.styles.ts

Note: we need to use both this style and Tab style to create a navigation component in each application. Also make sure that you use "large" size TabList.
Added navigation style to be able to create a navigation component in every application with the same style.

feat(styles): add navigation style

---

components/topbar/src/application-drawer.styles.ts
components/topbar/src/application-drawer.tsx
components/topbar/src/application-drawer.types.ts
components/topbar/src/application.styles.ts

Fix styling of application drawer according to mocks:
https://www.figma.com/file/vM5VurxI1uiWS3BEnULM8S/My-Systems-Portal?node-id=3509%3A105396&mode=dev
**Before:**
**After:**

fix(topbar): adjust application drawer styles

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.11.0

---

components/topbar/src/top-bar.styles.ts
components/topbar/src/top-bar.tsx
components/topbar/src/top-bar.types.ts
examples/src/components/top-bar.tsx

Added possibility to add custom content to center of topbar.

feat(topbar): add custom center content

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.12.0

---

components/stepper/src/step-symbol/use-step-symbol-styles.ts

Update colors of previous and current steps in stepper.
Before:
After:
Before:
After:
- Fixes [#(issue)](https://github.com/AxisCommunications/fluent-components/issues/189)

fix(stepper): update colors of previous and current steps

---

components/password-input/src/password-input.tsx

Enable Ref forwarding for `password-input` component

feat(passwordInput): enable ref forwarding

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.13.0

---

components/topbar/src/application-drawer.styles.ts
components/topbar/src/application-drawer.tsx
components/topbar/src/application-drawer.types.ts
components/topbar/src/application.styles.ts
examples/src/components/top-bar.tsx

Updates to application drawer after UX feedback
How it looks in Example:
https://github.com/AxisCommunications/fluent-components/assets/67627784/81597940-7deb-4e0f-8f5f-611813a6371c
How it looks with backend data:
https://github.com/AxisCommunications/fluent-components/assets/67627784/375bd800-6844-4a5f-bc98-568e41d4031e

fix(topbar): style updates to application drawer

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.14.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

Patch release with color updates

release: v8.14.1

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.15.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.16.0

---

components/topbar/package.json
components/topbar/src/application-utils.tsx
pnpm-lock.yaml

Use My Systems icon in Application Drawer in TopBar
- Fixes https://jira.se.axis.com/browse/LKPH-1627

fix(topbar): use correct my systems icon

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.17.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.19.0

---

components/topbar/src/application-drawer.styles.ts
components/topbar/src/application-drawer.tsx
components/topbar/src/application-drawer.types.ts
examples/src/components/top-bar.tsx

Application drawer trigger margin update (Left margin is now total 13 px).
https://www.figma.com/file/RqNwSw0bq0sjSXT6M5uJGQ/My-Systems-Components?node-id=285%3A9885&mode=dev

fix(topbar): adjust drawer trigger margins

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

Release with topbar drawer updates etc.

release: v8.20.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.20.1

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.20.2

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.20.3

---

components/topbar/src/application-drawer.styles.ts
components/topbar/src/application-drawer.tsx

Close the drawer by a click on the header.
Video with new behavior in left browser and old behavior in right browser:
https://github.com/AxisCommunications/fluent-components/assets/67627784/61c860f7-bf2f-4531-973d-9800111d47a5

feat(topbar): close drawer on header click

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.21.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.22.0

---

README.md

added illustartions package links and info to root readme

docs: add axis-illustrations to root README

---

README.md

Illustration link

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.23.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v8.24.0

---

components/topbar/src/application-utils.tsx

Update Icons for the various my-X flavors
Figma: https://www.figma.com/file/gzYMNRkkx4Y68Z19wJnDCn/AXIS-Fluent-Components?node-id=4496%3A14460&mode=dev

fix(topbar): update myX icons

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

Release with breaking change in topbar component.
topbar now requires @axiscommunications/fluent-theme version 9.0.0 or later since it uses the custom tokens added there.

release: v9.0.0

---

examples/src/stories/theme/components/color-tokens.tsx

Update the theme example page.
* Put Axis custom tokens on top
* Make the "headers" more clear
New look:
Old look:

chore: theme example updates

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.1.0

---

components/topbar/src/profile-menu.tsx
examples/src/components/top-bar.tsx

Update profile badge style.
* New background color colorPaletteMinkBackground2
* Remove ring when there are notifications
Before:
After:

fix(topbar): remove active ring and update color of profile badge

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.1.1

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.1.2

---

components/topbar/src/organization-menu.tsx
components/topbar/src/organization-menu.types.ts
components/topbar/src/organization.styles.ts
examples/src/components/top-bar.tsx

Add possibility to search organizations in topbar menu
Figma: https://www.figma.com/design/RqNwSw0bq0sjSXT6M5uJGQ/Implementation---My-Systems?node-id=297-1776&m=dev
https://github.com/user-attachments/assets/7e83b4e7-cc81-4e76-82a5-ca77905af744

feat(topbar): add ability to search organizations

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.2.0

---

components/topbar/src/organization-menu.tsx

Use fluent searcher component for search in organization dropdown
- Fixes https://jira.se.axis.com/browse/LKPH-1928

fix(topbar): use fluents own searchbox component

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.2.1

---

components/topbar/src/organization-menu.tsx

Only show the searchbox in the organisations dropdown if there are enough organisations to cause a scrollbar
- Fixes https://jira.se.axis.com/browse/LKPH-1928

fix(topbar): only show organization searchbox if needed

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.2.2

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.3.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.4.0

---

README.md
examples/src/stories/illustrations/illustration-page.tsx

remove notes from readme and new tag from illustration page

chore: remove experimental notes and new tag for illustrations

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.4.1

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v9.5.0

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

**components**
- slider bug fix
**maintenance**
- fix dependabot, working again
- various package bumps

release: v9.6.0

---

components/topbar/src/application-drawer.tsx

Always close drawer when clicking

fix(topbar): always close drawer after onChange action

---

components/topbar/src/application-drawer-v2.tsx

Remove bottom divider in topbar drawer v2.

fix(topbar): remove bottom divider

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.0.1

---

components/topbar/src/organization-menu.tsx
components/topbar/src/organization-menu.types.ts
components/topbar/src/organization.styles.ts
examples/src/components/top-bar.tsx

Topbar can now show a popover in the organization menu

feat(topbar): add popover to organization menu

---

components/topbar/src/application-drawer-v2.tsx

Drawer v2 can be closed on click on the Grid Dots icon

Close on menu

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.1.0

---

components/topbar/src/organization-menu.tsx

Add testId in organization menu

chore(topbar): add test id in organization menu

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.2.1

---

CHANGELOG.md
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.3.0

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.4.0

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.5.0

---

components/empty-view/src/constants.ts
components/empty-view/src/types.ts

This PR adds support for CodeError illustration in the EmptyView component.

feat: add code-error illustration to empty-view

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.6.0

---

components/topbar/src/languages.ts
components/topbar/src/translations.ts

feat (topbar): add romanian language

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

add romanian lang to topbar component

release: v10.7.0

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.8.0

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v10.9.0

---

.github/workflows/verify-page.yml

fixes:
after this i will align all actions to v4

chore: fix deprecated gh action

---

components/topbar/src/application-drawer-v2.styles.ts

Added spacing in topbar drawer title
- Fixes https://jira.se.axis.com/browse/LKPH-2251

fix(topbar): increase app icon spacing in v2 drawer trigger

---

.github/actions/setup-workspace/action.yml
.github/workflows/deploy.yml
.github/workflows/publish.yml
.github/workflows/verify-icons.yml
.github/workflows/verify-illustrations.yml
.github/workflows/verify-page.yml
.github/workflows/verify-tokens.yml
.github/workflows/verify.yml
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
icons/depcheck.yml
illustrations/depcheck.yml
illustrations/package.json
pnpm-lock.yaml
theme/package.json

- streamlines all jobs with same setup env action 
- also parallalize jobs that can be parallized => speed up checks (verify.yml)
- added check for unused dependencies to be run aswell 
- update checkout action from v3 to v4 for all actions/workflows

chore: use composite action for setup env

---

.github/workflows/deploy.yml
.github/workflows/publish.yml

revert composite action usage from publish and deploy

chore: revert pubish and deploy workflows

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v11.0.0

---

tools/generated/release/release.js
tools/src/release/release.ts

Add lint to the release script, since `pnpm version` changed some lines of package.json that does not match biome style rules.

chore: update release script

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

New illustration called "Sidebar"

release: v11.0.1

---

theme/src/themes/brand.ts

Adjusting color of the spinner background in light theme to create a better contrast against the background

style: Spinner background

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

relesae 11.1.0, changelog for details

release: v11.1.0

---

components/stepper/src/index.ts
components/stepper/src/stepper-dialog.types.ts
components/stepper/src/stepper.types.ts

- on request, export Step component from Stepper 
- minor break cause had to rename export type called Step.... to TStep (StepProps also taken)

chore: export step component

---

CHANGELOG.md
components/empty-view/package.json
components/password-input/package.json
components/slider/package.json
components/stepper/package.json
components/topbar/package.json
examples/package.json
hooks/package.json
icons/package.json
illustrations/package.json
package.json
styles/package.json
theme/package.json
tools/package.json

release: v11.5.1
